version: '3.8'

services:
  backend:
    build:
      context: ./EA-BackEnd-G3/EA_Backend_G3
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  frontend:
    build:
      context: ./EA-FrontEnd-G3/EA_Frontend_G3
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - frontend_network

  webreact:  # ✅ Correctamente alineado con 'frontend' y 'backend'
    build:
      context: ./EA-WebREACT-G3/EA_WebReact_G3
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network:

volumes:
  mongo-data:
